language: python
python: "2.7"
sudo: false

env:
  - TOX_ENV=py27-django12
  - TOX_ENV=py27-django13
  - TOX_ENV=py27-django14
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py33-django15
  - TOX_ENV=py33-django16
  - TOX_ENV=py33-django17
  - TOX_ENV=py33-django18
  - TOX_ENV=py34-django16
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19

matrix:
  fast_finish: true
  # Python 3.5 not yet available on travis, watch this to see when it is.
  allow_failures:
    - env:
      - TOX_ENV=py35-django18
      - TOX_ENV=py35-django19

install:
  - pip install tox --use-mirrors

script:
  - tox -e $TOX_ENV

notifications:
  irc: "irc.freenode.org#imagekit"
